# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 22:42
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_displayable_polls'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ('_order',)},
        ),
        migrations.AddField(
            model_name='choice',
            name='_order',
            field=mezzanine.core.fields.OrderField(null=True, verbose_name='Order'),
        ),
    ]
